### ISSUE TITLE
MathJax/Runestone/Menu/Chrome conflict creating Javascript errors

### ISSUE THREAD

**Issue by dbrianwalton** [PreTeXtBook/pretext#1967]
Opening https://pretextbook.org/examples/sample-article/html/section-interactive-exercises.html in Google Chrome on Mac (Version 111.0.5563.146 (Official Build) (x86_64)), the Javascript console reports a sequence of errors.

```
tex-chtml.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'replaceChild')
    at e.replace (tex-chtml.js:1:10078)
    at e.updateDocument (tex-chtml.js:1:198719)
    at t.updateDocument (tex-chtml.js:1:45671)
    at e.updateDocument (tex-chtml.js:1:191730)
    at e.updateDocument (tex-chtml.js:1:713701)
    at Object.renderDoc (tex-chtml.js:1:39265)
    at e.renderDoc (tex-chtml.js:1:39488)
    at t.render (tex-chtml.js:1:42447)
    at tex-chtml.js:1:26311
    at e (tex-chtml.js:1:742981)
```

Based on the file name, this appears to be a MathJax issue. It only appears on this particular page, suggesting there is a conflict between MathJax and Runestone and order of calls. When I put a break point on the offending line, it seems to only occur in relation to the MathJax that appears in the menu item that includes \(a]b\). Opening the same page on a Mac with Safari does not present the same errors.

I do not know how to determine why the same element appears to be updated so many times, or why it sometimes has a parentNode and other times does not.

(I thought I had broken something with my dynamic problem code because this happens there as well. I eventually discovered that it is a pre-existing condition.)

**Comment by bnmnetp** [comment]
@dbrianwalton 

I will take a look at the Runestone javascript for this PR.  But I will note for both you and @bjones1 that it is very important to use the following code when we need to make sure that MathJax is run on a component.

```javascript
if (typeof runestoneMathready !== "undefined") {
                    await runestoneMathReady.then(async () => await self.queueMathJax(item[0]));
                } 
```

I have slowly been getting Runestone component code to use that idiom, and it has fixed the race condition between Runestone and MathJax every time.

**Comment by dbrianwalton** [comment]
To be clear, I'm not sure how far back this happens to go. It occurs on the live branch, and has at least since February. I think this earlier message on pretext-dev was me seeing this same issue.

https://groups.google.com/g/pretext-dev/c/PZRrLmvHfwQ/m/6i8d4H1zAgAJ

- Brian

**Comment by bnmnetp** [comment]
@dbrianwalton , @bjones1 

I've reviewed Bryan's PR on the Runestone side, and there may definitely be a timing issue with mathjax if the problem statement has math in it.  The PR should be updated so that the div containing the problem statement as well as any answers containing math are queued up for mathjax rendering.
