### ISSUE TITLE
dependency pydantic==2.9.1 causes error

### ISSUE THREAD

**Issue by haraldschilly** [PreTeXtBook/pretext#2252]
I had to revert to `pydantic<2.6.0` to make version 2.6.2 of pretext work again. Otherwise I run into this. So, I suggest it should be updated to work with newer version of pydantic.

```
Traceback (most recent call last):                                                                                                  
  File "/usr/local/bin/pretext", line 5, in <module>                                                                                
    from pretext.cli import main                                                                                                    
  File "/usr/local/lib/python3.10/dist-packages/pretext/cli.py", line 35, in <module>                                               
    from .project import Project                                                                                                    
  File "/usr/local/lib/python3.10/dist-packages/pretext/project/__init__.py", line 30, in <module>                                  
    import pydantic_xml as pxml                                                                                                     
  File "/usr/local/lib/python3.10/dist-packages/pydantic_xml/__init__.py", line 5, in <module>                                      
    from . import config, errors, model                                                                                             
  File "/usr/local/lib/python3.10/dist-packages/pydantic_xml/model.py", line 13, in <module>                                        
    from .serializers.factories.model import BaseModelSerializer                                                                    
  File "/usr/local/lib/python3.10/dist-packages/pydantic_xml/serializers/__init__.py", line 1, in <module>                          
    from . import factories, serializer                                                                                             
  File "/usr/local/lib/python3.10/dist-packages/pydantic_xml/serializers/factories/__init__.py", line 1, in <module>                
    from . import heterogeneous, homogeneous, is_instance, mapping, model, primitive, raw, tagged_union, typed_mapping              
  File "/usr/local/lib/python3.10/dist-packages/pydantic_xml/serializers/factories/heterogeneous.py", line 11, in <module>          
    class ElementSerializer(Serializer):                                                                                            
  File "/usr/local/lib/python3.10/dist-packages/pydantic_xml/serializers/factories/heterogeneous.py", line 13, in ElementSerializer 
    def from_core_schema(cls, schema: pcs.TuplePositionalSchema, ctx: Serializer.Context) -> 'ElementSerializer':                   
  File "/usr/local/lib/python3.10/dist-packages/pydantic_core/core_schema.py", line 4132, in __getattr__                            
    raise AttributeError(f"module 'pydantic_core' has no attribute '{attr_name}'")                                                  
AttributeError: module 'pydantic_core' has no attribute 'TuplePositionalSchema'. Did you mean: 'tuple_positional_schema'?           
```

**Comment by oscarlevin** [comment]
I'm not able to replicate this.  I'm using the following versions of the pydantic packages:

pydantic             2.9.1
pydantic_core        2.23.3
pydantic-xml         2.12.1

It looks like this was an issue before 2.9.0: https://github.com/dapper91/pydantic-xml/issues/167

**Comment by haraldschilly** [comment]
Thank you for checking, I got it to work as well. I think I only updated pydantic, but not that xml package as well.
